// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/prebid.proto

public final class Prebid {
  private Prebid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface uidCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uidCollection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 expirationBase = 1;</code>
     * @return The expirationBase.
     */
    long getExpirationBase();

    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    java.util.List<Prebid.uidCollection.uidObject> 
        getUidsList();
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    Prebid.uidCollection.uidObject getUids(int index);
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    int getUidsCount();
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    java.util.List<? extends Prebid.uidCollection.uidObjectOrBuilder> 
        getUidsOrBuilderList();
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    Prebid.uidCollection.uidObjectOrBuilder getUidsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code uidCollection}
   */
  public static final class uidCollection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uidCollection)
      uidCollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use uidCollection.newBuilder() to construct.
    private uidCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private uidCollection() {
      uids_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new uidCollection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private uidCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              expirationBase_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                uids_ = new java.util.ArrayList<Prebid.uidCollection.uidObject>();
                mutable_bitField0_ |= 0x00000001;
              }
              uids_.add(
                  input.readMessage(Prebid.uidCollection.uidObject.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Prebid.internal_static_uidCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Prebid.internal_static_uidCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Prebid.uidCollection.class, Prebid.uidCollection.Builder.class);
    }

    public interface uidObjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:uidCollection.uidObject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string bidder = 1;</code>
       * @return The bidder.
       */
      java.lang.String getBidder();
      /**
       * <code>string bidder = 1;</code>
       * @return The bytes for bidder.
       */
      com.google.protobuf.ByteString
          getBidderBytes();

      /**
       * <code>string uid = 2;</code>
       * @return The uid.
       */
      java.lang.String getUid();
      /**
       * <code>string uid = 2;</code>
       * @return The bytes for uid.
       */
      com.google.protobuf.ByteString
          getUidBytes();

      /**
       * <code>uint32 expirationOffset = 3;</code>
       * @return The expirationOffset.
       */
      int getExpirationOffset();
    }
    /**
     * Protobuf type {@code uidCollection.uidObject}
     */
    public static final class uidObject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:uidCollection.uidObject)
        uidObjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use uidObject.newBuilder() to construct.
      private uidObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private uidObject() {
        bidder_ = "";
        uid_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new uidObject();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private uidObject(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                bidder_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                uid_ = s;
                break;
              }
              case 24: {

                expirationOffset_ = input.readUInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Prebid.internal_static_uidCollection_uidObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Prebid.internal_static_uidCollection_uidObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Prebid.uidCollection.uidObject.class, Prebid.uidCollection.uidObject.Builder.class);
      }

      public static final int BIDDER_FIELD_NUMBER = 1;
      private volatile java.lang.Object bidder_;
      /**
       * <code>string bidder = 1;</code>
       * @return The bidder.
       */
      @java.lang.Override
      public java.lang.String getBidder() {
        java.lang.Object ref = bidder_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bidder_ = s;
          return s;
        }
      }
      /**
       * <code>string bidder = 1;</code>
       * @return The bytes for bidder.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBidderBytes() {
        java.lang.Object ref = bidder_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int UID_FIELD_NUMBER = 2;
      private volatile java.lang.Object uid_;
      /**
       * <code>string uid = 2;</code>
       * @return The uid.
       */
      @java.lang.Override
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        }
      }
      /**
       * <code>string uid = 2;</code>
       * @return The bytes for uid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EXPIRATIONOFFSET_FIELD_NUMBER = 3;
      private int expirationOffset_;
      /**
       * <code>uint32 expirationOffset = 3;</code>
       * @return The expirationOffset.
       */
      @java.lang.Override
      public int getExpirationOffset() {
        return expirationOffset_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getBidderBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bidder_);
        }
        if (!getUidBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
        }
        if (expirationOffset_ != 0) {
          output.writeUInt32(3, expirationOffset_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getBidderBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bidder_);
        }
        if (!getUidBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
        }
        if (expirationOffset_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, expirationOffset_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Prebid.uidCollection.uidObject)) {
          return super.equals(obj);
        }
        Prebid.uidCollection.uidObject other = (Prebid.uidCollection.uidObject) obj;

        if (!getBidder()
            .equals(other.getBidder())) return false;
        if (!getUid()
            .equals(other.getUid())) return false;
        if (getExpirationOffset()
            != other.getExpirationOffset()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BIDDER_FIELD_NUMBER;
        hash = (53 * hash) + getBidder().hashCode();
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
        hash = (37 * hash) + EXPIRATIONOFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getExpirationOffset();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Prebid.uidCollection.uidObject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Prebid.uidCollection.uidObject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Prebid.uidCollection.uidObject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Prebid.uidCollection.uidObject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Prebid.uidCollection.uidObject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Prebid.uidCollection.uidObject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Prebid.uidCollection.uidObject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code uidCollection.uidObject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:uidCollection.uidObject)
          Prebid.uidCollection.uidObjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Prebid.internal_static_uidCollection_uidObject_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Prebid.internal_static_uidCollection_uidObject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Prebid.uidCollection.uidObject.class, Prebid.uidCollection.uidObject.Builder.class);
        }

        // Construct using Prebid.uidCollection.uidObject.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bidder_ = "";

          uid_ = "";

          expirationOffset_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Prebid.internal_static_uidCollection_uidObject_descriptor;
        }

        @java.lang.Override
        public Prebid.uidCollection.uidObject getDefaultInstanceForType() {
          return Prebid.uidCollection.uidObject.getDefaultInstance();
        }

        @java.lang.Override
        public Prebid.uidCollection.uidObject build() {
          Prebid.uidCollection.uidObject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Prebid.uidCollection.uidObject buildPartial() {
          Prebid.uidCollection.uidObject result = new Prebid.uidCollection.uidObject(this);
          result.bidder_ = bidder_;
          result.uid_ = uid_;
          result.expirationOffset_ = expirationOffset_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Prebid.uidCollection.uidObject) {
            return mergeFrom((Prebid.uidCollection.uidObject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Prebid.uidCollection.uidObject other) {
          if (other == Prebid.uidCollection.uidObject.getDefaultInstance()) return this;
          if (!other.getBidder().isEmpty()) {
            bidder_ = other.bidder_;
            onChanged();
          }
          if (!other.getUid().isEmpty()) {
            uid_ = other.uid_;
            onChanged();
          }
          if (other.getExpirationOffset() != 0) {
            setExpirationOffset(other.getExpirationOffset());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Prebid.uidCollection.uidObject parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Prebid.uidCollection.uidObject) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object bidder_ = "";
        /**
         * <code>string bidder = 1;</code>
         * @return The bidder.
         */
        public java.lang.String getBidder() {
          java.lang.Object ref = bidder_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            bidder_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string bidder = 1;</code>
         * @return The bytes for bidder.
         */
        public com.google.protobuf.ByteString
            getBidderBytes() {
          java.lang.Object ref = bidder_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            bidder_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string bidder = 1;</code>
         * @param value The bidder to set.
         * @return This builder for chaining.
         */
        public Builder setBidder(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          bidder_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string bidder = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearBidder() {
          
          bidder_ = getDefaultInstance().getBidder();
          onChanged();
          return this;
        }
        /**
         * <code>string bidder = 1;</code>
         * @param value The bytes for bidder to set.
         * @return This builder for chaining.
         */
        public Builder setBidderBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          bidder_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object uid_ = "";
        /**
         * <code>string uid = 2;</code>
         * @return The uid.
         */
        public java.lang.String getUid() {
          java.lang.Object ref = uid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uid_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string uid = 2;</code>
         * @return The bytes for uid.
         */
        public com.google.protobuf.ByteString
            getUidBytes() {
          java.lang.Object ref = uid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uid = 2;</code>
         * @param value The uid to set.
         * @return This builder for chaining.
         */
        public Builder setUid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          uid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string uid = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearUid() {
          
          uid_ = getDefaultInstance().getUid();
          onChanged();
          return this;
        }
        /**
         * <code>string uid = 2;</code>
         * @param value The bytes for uid to set.
         * @return This builder for chaining.
         */
        public Builder setUidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          uid_ = value;
          onChanged();
          return this;
        }

        private int expirationOffset_ ;
        /**
         * <code>uint32 expirationOffset = 3;</code>
         * @return The expirationOffset.
         */
        @java.lang.Override
        public int getExpirationOffset() {
          return expirationOffset_;
        }
        /**
         * <code>uint32 expirationOffset = 3;</code>
         * @param value The expirationOffset to set.
         * @return This builder for chaining.
         */
        public Builder setExpirationOffset(int value) {
          
          expirationOffset_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 expirationOffset = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearExpirationOffset() {
          
          expirationOffset_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:uidCollection.uidObject)
      }

      // @@protoc_insertion_point(class_scope:uidCollection.uidObject)
      private static final Prebid.uidCollection.uidObject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Prebid.uidCollection.uidObject();
      }

      public static Prebid.uidCollection.uidObject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<uidObject>
          PARSER = new com.google.protobuf.AbstractParser<uidObject>() {
        @java.lang.Override
        public uidObject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new uidObject(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<uidObject> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<uidObject> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Prebid.uidCollection.uidObject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int EXPIRATIONBASE_FIELD_NUMBER = 1;
    private long expirationBase_;
    /**
     * <code>uint64 expirationBase = 1;</code>
     * @return The expirationBase.
     */
    @java.lang.Override
    public long getExpirationBase() {
      return expirationBase_;
    }

    public static final int UIDS_FIELD_NUMBER = 2;
    private java.util.List<Prebid.uidCollection.uidObject> uids_;
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    @java.lang.Override
    public java.util.List<Prebid.uidCollection.uidObject> getUidsList() {
      return uids_;
    }
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Prebid.uidCollection.uidObjectOrBuilder> 
        getUidsOrBuilderList() {
      return uids_;
    }
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    @java.lang.Override
    public int getUidsCount() {
      return uids_.size();
    }
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    @java.lang.Override
    public Prebid.uidCollection.uidObject getUids(int index) {
      return uids_.get(index);
    }
    /**
     * <code>repeated .uidCollection.uidObject uids = 2;</code>
     */
    @java.lang.Override
    public Prebid.uidCollection.uidObjectOrBuilder getUidsOrBuilder(
        int index) {
      return uids_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (expirationBase_ != 0L) {
        output.writeUInt64(1, expirationBase_);
      }
      for (int i = 0; i < uids_.size(); i++) {
        output.writeMessage(2, uids_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (expirationBase_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, expirationBase_);
      }
      for (int i = 0; i < uids_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, uids_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Prebid.uidCollection)) {
        return super.equals(obj);
      }
      Prebid.uidCollection other = (Prebid.uidCollection) obj;

      if (getExpirationBase()
          != other.getExpirationBase()) return false;
      if (!getUidsList()
          .equals(other.getUidsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXPIRATIONBASE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpirationBase());
      if (getUidsCount() > 0) {
        hash = (37 * hash) + UIDS_FIELD_NUMBER;
        hash = (53 * hash) + getUidsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Prebid.uidCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Prebid.uidCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Prebid.uidCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Prebid.uidCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Prebid.uidCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Prebid.uidCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Prebid.uidCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Prebid.uidCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Prebid.uidCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Prebid.uidCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Prebid.uidCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Prebid.uidCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Prebid.uidCollection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code uidCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uidCollection)
        Prebid.uidCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Prebid.internal_static_uidCollection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Prebid.internal_static_uidCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Prebid.uidCollection.class, Prebid.uidCollection.Builder.class);
      }

      // Construct using Prebid.uidCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUidsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        expirationBase_ = 0L;

        if (uidsBuilder_ == null) {
          uids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          uidsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Prebid.internal_static_uidCollection_descriptor;
      }

      @java.lang.Override
      public Prebid.uidCollection getDefaultInstanceForType() {
        return Prebid.uidCollection.getDefaultInstance();
      }

      @java.lang.Override
      public Prebid.uidCollection build() {
        Prebid.uidCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Prebid.uidCollection buildPartial() {
        Prebid.uidCollection result = new Prebid.uidCollection(this);
        int from_bitField0_ = bitField0_;
        result.expirationBase_ = expirationBase_;
        if (uidsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            uids_ = java.util.Collections.unmodifiableList(uids_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.uids_ = uids_;
        } else {
          result.uids_ = uidsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Prebid.uidCollection) {
          return mergeFrom((Prebid.uidCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Prebid.uidCollection other) {
        if (other == Prebid.uidCollection.getDefaultInstance()) return this;
        if (other.getExpirationBase() != 0L) {
          setExpirationBase(other.getExpirationBase());
        }
        if (uidsBuilder_ == null) {
          if (!other.uids_.isEmpty()) {
            if (uids_.isEmpty()) {
              uids_ = other.uids_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUidsIsMutable();
              uids_.addAll(other.uids_);
            }
            onChanged();
          }
        } else {
          if (!other.uids_.isEmpty()) {
            if (uidsBuilder_.isEmpty()) {
              uidsBuilder_.dispose();
              uidsBuilder_ = null;
              uids_ = other.uids_;
              bitField0_ = (bitField0_ & ~0x00000001);
              uidsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUidsFieldBuilder() : null;
            } else {
              uidsBuilder_.addAllMessages(other.uids_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Prebid.uidCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Prebid.uidCollection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long expirationBase_ ;
      /**
       * <code>uint64 expirationBase = 1;</code>
       * @return The expirationBase.
       */
      @java.lang.Override
      public long getExpirationBase() {
        return expirationBase_;
      }
      /**
       * <code>uint64 expirationBase = 1;</code>
       * @param value The expirationBase to set.
       * @return This builder for chaining.
       */
      public Builder setExpirationBase(long value) {
        
        expirationBase_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 expirationBase = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpirationBase() {
        
        expirationBase_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<Prebid.uidCollection.uidObject> uids_ =
        java.util.Collections.emptyList();
      private void ensureUidsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          uids_ = new java.util.ArrayList<Prebid.uidCollection.uidObject>(uids_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Prebid.uidCollection.uidObject, Prebid.uidCollection.uidObject.Builder, Prebid.uidCollection.uidObjectOrBuilder> uidsBuilder_;

      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public java.util.List<Prebid.uidCollection.uidObject> getUidsList() {
        if (uidsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(uids_);
        } else {
          return uidsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public int getUidsCount() {
        if (uidsBuilder_ == null) {
          return uids_.size();
        } else {
          return uidsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Prebid.uidCollection.uidObject getUids(int index) {
        if (uidsBuilder_ == null) {
          return uids_.get(index);
        } else {
          return uidsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder setUids(
          int index, Prebid.uidCollection.uidObject value) {
        if (uidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUidsIsMutable();
          uids_.set(index, value);
          onChanged();
        } else {
          uidsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder setUids(
          int index, Prebid.uidCollection.uidObject.Builder builderForValue) {
        if (uidsBuilder_ == null) {
          ensureUidsIsMutable();
          uids_.set(index, builderForValue.build());
          onChanged();
        } else {
          uidsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder addUids(Prebid.uidCollection.uidObject value) {
        if (uidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUidsIsMutable();
          uids_.add(value);
          onChanged();
        } else {
          uidsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder addUids(
          int index, Prebid.uidCollection.uidObject value) {
        if (uidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUidsIsMutable();
          uids_.add(index, value);
          onChanged();
        } else {
          uidsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder addUids(
          Prebid.uidCollection.uidObject.Builder builderForValue) {
        if (uidsBuilder_ == null) {
          ensureUidsIsMutable();
          uids_.add(builderForValue.build());
          onChanged();
        } else {
          uidsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder addUids(
          int index, Prebid.uidCollection.uidObject.Builder builderForValue) {
        if (uidsBuilder_ == null) {
          ensureUidsIsMutable();
          uids_.add(index, builderForValue.build());
          onChanged();
        } else {
          uidsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder addAllUids(
          java.lang.Iterable<? extends Prebid.uidCollection.uidObject> values) {
        if (uidsBuilder_ == null) {
          ensureUidsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, uids_);
          onChanged();
        } else {
          uidsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder clearUids() {
        if (uidsBuilder_ == null) {
          uids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          uidsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Builder removeUids(int index) {
        if (uidsBuilder_ == null) {
          ensureUidsIsMutable();
          uids_.remove(index);
          onChanged();
        } else {
          uidsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Prebid.uidCollection.uidObject.Builder getUidsBuilder(
          int index) {
        return getUidsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Prebid.uidCollection.uidObjectOrBuilder getUidsOrBuilder(
          int index) {
        if (uidsBuilder_ == null) {
          return uids_.get(index);  } else {
          return uidsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public java.util.List<? extends Prebid.uidCollection.uidObjectOrBuilder> 
           getUidsOrBuilderList() {
        if (uidsBuilder_ != null) {
          return uidsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(uids_);
        }
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Prebid.uidCollection.uidObject.Builder addUidsBuilder() {
        return getUidsFieldBuilder().addBuilder(
            Prebid.uidCollection.uidObject.getDefaultInstance());
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public Prebid.uidCollection.uidObject.Builder addUidsBuilder(
          int index) {
        return getUidsFieldBuilder().addBuilder(
            index, Prebid.uidCollection.uidObject.getDefaultInstance());
      }
      /**
       * <code>repeated .uidCollection.uidObject uids = 2;</code>
       */
      public java.util.List<Prebid.uidCollection.uidObject.Builder> 
           getUidsBuilderList() {
        return getUidsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Prebid.uidCollection.uidObject, Prebid.uidCollection.uidObject.Builder, Prebid.uidCollection.uidObjectOrBuilder> 
          getUidsFieldBuilder() {
        if (uidsBuilder_ == null) {
          uidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Prebid.uidCollection.uidObject, Prebid.uidCollection.uidObject.Builder, Prebid.uidCollection.uidObjectOrBuilder>(
                  uids_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          uids_ = null;
        }
        return uidsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:uidCollection)
    }

    // @@protoc_insertion_point(class_scope:uidCollection)
    private static final Prebid.uidCollection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Prebid.uidCollection();
    }

    public static Prebid.uidCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<uidCollection>
        PARSER = new com.google.protobuf.AbstractParser<uidCollection>() {
      @java.lang.Override
      public uidCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new uidCollection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<uidCollection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<uidCollection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Prebid.uidCollection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uidCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uidCollection_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uidCollection_uidObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uidCollection_uidObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026resources/prebid.proto\"\223\001\n\ruidCollecti" +
      "on\022\026\n\016expirationBase\030\001 \001(\004\022&\n\004uids\030\002 \003(\013" +
      "2\030.uidCollection.uidObject\032B\n\tuidObject\022" +
      "\016\n\006bidder\030\001 \001(\t\022\013\n\003uid\030\002 \001(\t\022\030\n\020expirati" +
      "onOffset\030\003 \001(\rb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_uidCollection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uidCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uidCollection_descriptor,
        new java.lang.String[] { "ExpirationBase", "Uids", });
    internal_static_uidCollection_uidObject_descriptor =
      internal_static_uidCollection_descriptor.getNestedTypes().get(0);
    internal_static_uidCollection_uidObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uidCollection_uidObject_descriptor,
        new java.lang.String[] { "Bidder", "Uid", "ExpirationOffset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
